### ISSUE TITLE
2x ARM CI for Apache CouchDB

### ISSUE THREAD

**Issue by wohali** [WorksOnArm/cluster#174]
### Name, email, company, job title

* Joan Touzet
* wohali@apache.org
* Apache Software Foundation
* Director; also, CouchDB Project Management Committee

### Project Title and description

Apache CouchDB - "Apache CouchDB is a database that completely embraces the web. Store your data with JSON documents. Access your documents with your web browser, via HTTP. Query, combine, and transform your documents with JavaScript. Apache CouchDB works well with modern web and mobile apps. CouchDB's killer feature is its ability to distribute data efficiently using Apache CouchDB’s incremental replication. Apache CouchDB supports master-master setups with automatic conflict detection."

### Which members of the community would benefit from your work?

All users on `aarch64`. We intend to use these images for mandatory CI before we approve and release the `aarch64` CouchDB docker image support.

### Is the code that you’re going to run 100% open source? If so, what is the URL or URLs where it is located?

Yes! https://github.com/apache/couchdb/

### What infrastructure (computing resources and network access) do you need? (see: https://www.packet.net/bare-metal/)?

2x ongoing nodes on which we can run Jenkins CI workers. We need 2x nodes to ensure availability, especially during busy development sessions.

The ASF's nodes won't work for us at the moment, because we will intend to use these nodes to auto-publish new binaries, and we cannot store those credentials on the shared ASF nodes. We are instead establishing our own Jenkins master and will need separate machines.

### Describe the continuous integration (CI) system in use or desired for this project.

Jenkins CI / Cloudbees Core.

### Please state your contributions to the open source community and any other relevant initiatives

The Apache Software Foundation is celebrating its twentieth anniversary this year, and its success speaks for itself. CouchDB is 10 years old this year, and has over 5+ million downloads from Docker Hub, over 1mil from our binary packages repo, and we are eager to expand this to the aarch64 platform.

**Comment by vielmetti** [comment]
Thanks Joan! We reviewed this this morning, and a few more questions came up.

### Please provide examples of deployments, use cases, or technologies enabled by CouchDB

We're looking especially for indications where CouchDB is being used in deployments that would be amenable to using Arm infrastructure for demonstration and production purposes.

### Where does the CouchDB project communicate about its successes?

We're also looking for a venue in which the CouchDB project could blog or otherwise write about what it's doing on Arm once the initial CI is set up.

thanks @wohali and looking forward to hearing from you!  Ed

**Comment by vielmetti** [comment]
One more question for now:

### Which specific version of Erlang are you planning to test against, and do you have an arm64 supported version from that project?

I note in your "Installing from source" document draft at http://guide.couchdb.org/draft/source.html that there is a specific Erlang dependency, want to be sure that we have that piece of the effort covered.

**Comment by wohali** [comment]
@vielmetti we'll be running Jenkins workers that use Docker for all runs, so no need to install anything for us other than Docker.

I've asked @kocolosk and @janl to comment on the first 2 questions, they should be able to provide better context as I am in transit for a few more days.

**Comment by wohali** [comment]
@vielmetti oh, if you want to see how we build our Docker instances, @lag-linaro carried us up that hill, see https://github.com/apache/couchdb-ci for the gory details. (Thanks again!)

**Comment by kocolosk** [comment]
> Where does the CouchDB project communicate about its successes?

The project does maintain its own blog at https://blog.couchdb.org. The Neighbourhoodie team also has a blog at https://neighbourhood.ie/blog/ which includes a lot of CouchDB material. Occasionally IBM will also feature CouchDB content, e.g. https://www.ibm.com/cloud/blog/new-builders/database-deep-dives-couchdb or https://developer.ibm.com/dwblog/2016/apache-couchdb-2-0/.

> Please provide examples of deployments, use cases, or technologies enabled by CouchDB

CouchDB is a great general-purpose database for building web applications, but the feature that most significantly differentiates it from the competition is its rich support for active/active replication across devices of many shapes and sizes using pure HTTPS. We have customers who use this to sync together multiple cloud regions, but also customers who create replication topologies between centralized data centers and a large number of distributed smaller devices (tablets, back-of-store systems, etc.) It's easy for me to see ARM playing an important role in the latter use case given its historical strength in smaller devices, although frankly ARM is increasingly relevant in hyperscale cloud facilities too.

**Comment by lag-linaro** [comment]
Great to see CouchDB applying to WorksOnArm.

+1 from me.

**Comment by wohali** [comment]
@vielmetti is there more we (Apache CouchDB) need to do to move this forward?

**Comment by vielmetti** [comment]
@wohali I will have time on task for this Tuesday or Wednesday depending on how quickly I recover from All Systems Go! and a few days of travel to 6 time zones away (DTW-TXL).

From the sounds of it it might be useful to demonstrate this tool on a distributed network - we should be able to get you spot-market time on systems in a variety of data centers to validate - and since it's spot market we can force a system shutdown to see how the whole thing reacts.

@lag-linaro Thanks for the :+1: that's a useful data point. If you can privately send me any relevant contact info on the Arm side that would help so that I can cross-connect efforts to ensure alignment and acknowledgement of mutual goals.

I am doing a whole bunch of prep for Arm Techcon Oct 8-10, rest assured that this is important to that effort.

**Comment by vielmetti** [comment]
Recovering from jet lag took longer than expected, but this is all approved and just awaiting time on task to get it set up. I've added it to the TechCon milestone, and if anyone will be there for that event please flag me down per the schedule in #177.
