### ISSUE TITLE
ROS - Works On Arm Sponsored

### ISSUE THREAD

**Issue by nuclearsandwich** [WorksOnArm/cluster#285]
If you are interested in filing a request for access to the Works on Arm test and 
CI infrastructure, please fill out the details below.

Proposals will be evaluated on a biweekly cycle or on a best effort basis by Arm and Equinix Metal.

### Name, email, company, job title

Steven! Ragnarök, <steven@openrobotics.org>, Open Robotics, Infrastructure project lead
Tully Foote, <tfoote@openrobotics.org>, Open Robotics, Community and business development manager

### Project Title and description

[ROS](https://www.ros.org/) is a set of software libraries and tools that help you build robot applications. From drivers to state-of-the-art algorithms, and with powerful developer tools.

### Describe your use case for these machines

ROS is a federated project with several distributions each containing many hundreds of packages.
We will use this machine on our ROS 2 build farm to build native ARM packages for our community.

### Which members of the community would benefit from your work?

All community members who develop, test, or deploy on ARM-based devices or robots will be able to use packages built on the sponsored hosts.

### Is the code that you’re going to run 100% open source? 

All packages built on the ROS build farm are open source licensed.

The distribution metadata for ROS can be found in the [ros/rosdistro](https://github.com/ros/rosdistro/) repository which contains links to source repositories for ROS packages.

### Does this project require ARMv8.2 (Yes/No/Not Sure)? If Yes, please provide details 

No, but ideally we would be able to natively build armhf packages as well.

### What infrastructure (computing resources and network access) do you need?

Based on separate discussions with the Equinix Metal team we would like ongoing access to one Single Socket (Mt. Snow): 80 Cores, 128GB RAM (8x 16GB), 1TB NVMe U.2 SSD, 1x 25GbE NIC running Ubuntu 20.04.

The infrastructure is operated by Open Robotics.

### Describe / Name the continuous integration (CI) system for this project.

[build.ros2.org](https://buiild.ros2.org) is a Jenkins build farm cluster we use for producing ROS 2 packages. This machine will be the primary ARM-native host in that cluster.

### Please state your contributions to the open source community and any other relevant initiatives.

Open Robotics has been providing ARM packages for ROS with varying degrees for over five years.
With previous support from Works On Arm we have been able to make Ubuntu Linux on ARM64 a tier 1 supported platform for ROS 2.

**Comment by pgmwoa** [comment]
We are in the process of getting the servers ready for you. You will get an email as soon as the hardware is reserved and ready for use.

**Comment by nuclearsandwich** [comment]
Thank you!

**Comment by pgmwoa** [comment]
Necessary infrastructure is reserved. Please refer to the welcome email for instructions on how to use the reserved server and the supporting resources. We will be looking forward for your feedback / experience on new servers.

**Comment by shipra-ps** [comment]
Hi Team,

I have sent one important communication to you over email on 10th Jul'24. Request you to check that and acknowledge.

Regards,
Shipra Snehi
WoA Program Team

@shipra-ps


Add a comment
Comment
 
Add your comment here...
 
Remember, contributions to this repository should follow our GitHub Community Guidelines.
Assignees
@[vielmetti](https://github.com/vielmetti)
vielmetti
@[bhumikpatel](https://github.com/bhumikpatel)
bhumikpatel
@[pgmwoa](https://github.com/pgmwoa)
pgmwoa
Labels
[approved](https://github.com/WorksOnArm/equinix-metal-arm64-cluster/labels/approved)
[hardware/ampere-altra](https://github.com/WorksOnArm/equinix-metal-arm64-cluster/labels/hardware%2Fampere-altra)
Projects
None yet
Milestone
No milestone
Development
 for this issue or link a pull request.

Notifications
Customize
You’re receiving notifications because you commented.
5 participants
@vielmetti
@benjyw
@bhumikpatel
@pgmwoa
@shipra-ps
 
 Delete issue
