### ISSUE TITLE
armv8 hardware for Alpine Linux

### ISSUE THREAD

**Issue by vielmetti** [WorksOnArm/cluster#50]
Per a request from the Alpine Linux team, we are looking at hardware to support their build infrastructure.

https://alpinelinux.org/

**Comment by vielmetti** [comment]
https://twitter.com/n_copa/status/980866527409987586

![96 core kernel compile](https://pbs.twimg.com/media/DZy8dUcWsAASMcN.png)

**Comment by clandmeter** [comment]
Alpine Linux has recently switched from GitHub to our self hosted
GitLab based completely on Alpine Linux. The two main reasons for this 
switch are

1. Limit vendor lock in by using Open Source solutions.
2. Support CI for all Alpine Linux Architectures.

In our previous GitHub workflow we were happily using Drone CI with
support for 5 architectures x86, x86_64, aarch64, armv7, armhf. While
this brought us a much needed increase in architectures compared to
our previous Travis CI we were still lacking on our two other
architectures s390x and ppc64le. These two architectures are also much
more difficult for our developers to develop on due to the lack of 
available hardware so CI for them would be very useful. We have since 
received additional machines to setup CI for these architectures so
these are now added to our CI workflow.

For ARM we already had two machines from our sponsor packet.com, one
ThunderX and one Ampere where the Ampere has the added benefits of
support running in 32bit mode and is much faster in single thread
operations. Currently we share these machines for both our official
builders and for GitLab CI. Although these servers are very powerful
we need to mix LXC for builders with docker in KVM for our CI runners.
This starts to add up when developers are active and push to several
branches/arches and all these jobs run at the same time on single/dual
machines in both LXC containers and docker containers in KVM. I have
addresses theses issues with Ed and also notified him about a memory
issue we are having with the ThunderX machine, and this is thereason
he has asked me to write some information about our setup here.

For GitLab CI we have also setup our own projects for the runners.
This means all our CI infrastructure is based on Alpine Linux as much
as possible. This was also needed to get all architectures available
as GitLab did not support them. One of our developers has done a great
job in setting things up, you can find his work here:

https://gitlab.alpinelinux.org/alpine/infra/docker and
https://hub.docker.com/u/alpinelinux.

We are really happy with the support we have received and hope we can
continue this in the future. If you need any more details about our CI
or related please feel free to get in touch with us.

Alpine Linux Team

**Comment by vielmetti** [comment]
Thanks @clandmeter !
